// <auto-generated />
namespace Yufu.Notify.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20151021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20151021));
        
        string IMigrationMetadata.Id
        {
            get { return "201510210938328_2015-10-21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
